### ISSUE TITLE
Creación de los modelos y vistas de archivos pendientes

### ISSUE THREAD

**Issue by Jat294** [Jat294/password-manager-web#5]

**Comment by MigueVar11** [comment]
## Issue: Creación de los Modelos y Vistas de Archivos Pendientes

### Descripción:
Se requiere la implementación de los modelos y vistas correspondientes para la gestión de archivos pendientes. En una fase previa, se realizaron las siguientes acciones:
1. **Creación de las Vistas del Page**: Se crearon las vistas del page de manera correcta, proporcionando una estructura clara y funcional.
2. **Mejora del Dashboard Principal**: Se realizaron mejoras significativas en el dashboard principal, optimizando su visualización y usabilidad.

### Requisitos:
- **Modelos**: 
  - Definir y crear los modelos necesarios que representen los archivos pendientes.
  - Incluir todos los atributos y relaciones relevantes.

- **Vistas**: 
  - Implementar las vistas que permitan la visualización, adición, edición y eliminación de archivos pendientes.

- **Integración**: 
  - Asegurar la integración adecuada de los nuevos modelos y vistas con el dashboard principal.

- **Validaciones y Pruebas**: 
  - Implementar validaciones para los datos y realizar pruebas exhaustivas para asegurar la funcionalidad correcta.

### Objetivos:
- Mejorar la gestión y seguimiento de archivos pendientes.
- Mantener la coherencia y usabilidad en la interfaz de usuario.
- Asegurar la correcta funcionalidad y rendimiento del sistema.

**Comment by MigueVar11** [comment]
Cerrado
