### ISSUE TITLE
se implemente la funcionalida de la vista Notifications

### ISSUE THREAD

**Issue by Alejovg1997** [Jat294/password-manager-web#6]

**Comment by Alejovg1997** [comment]
1. Título del Issue

Implementación del Sistema de Notificaciones

- Descripción

Se ha implementado un sistema de notificaciones en la carpeta js/Notifications que permite gestionar y visualizar notificaciones importantes relacionadas con la gestión de contraseñas y cuentas de usuario. Este sistema incluye las siguientes funcionalidades:

- Funcionalidades

Agregar Notificación al Actualizar Contraseña:

Cada vez que un usuario actualiza su contraseña, se genera una notificación informando sobre el cambio.
Agregar Notificación al Iniciar Sesión:

Se crea una notificación cada vez que un usuario inicia sesión, especialmente si es desde un dispositivo nuevo.
Agregar Notificación al Eliminar Cuenta:

- Cuando un usuario elimina su cuenta, se registra una notificación correspondiente.

Estructura del Código
index.js: Este archivo contiene la lógica principal del sistema de notificaciones. Incluye funciones para agregar notificaciones y gestionar el estado de las mismas.
Componentes:
Notifications.jsx: Componente que muestra la lista de notificaciones.
NotificationItem.jsx: Componente que representa cada notificación individual.
Ejemplo de Uso
Para utilizar el sistema de notificaciones, simplemente llama a la función correspondiente (por ejemplo, addNotification) en los eventos mencionados (actualización de contraseña, inicio de sesión, eliminación de cuenta).

- Consideraciones

Asegúrate de que el sistema esté bien integrado con el resto de la aplicación.
Revisa la interfaz de usuario para garantizar que las notificaciones se muestren de manera clara y accesible.

**Comment by MigueVar11** [comment]
Excelente
